# Child Pipeline Example - Receives trace context from parent
# This pipeline is triggered by the parent and creates correlated spans

stages:
  - validate
  - deploy-prod
  - .post

default:
  tags:
    - my-runner-tag

variables:
  OTEL_EXPORTER_OTLP_ENDPOINT: "otel-collector:4318"

# Show received trace context
validate:
  stage: validate
  script:
    - echo "Child pipeline started"
    - echo "Parent pipeline URL:\ $PARENT_PIPELINE_URL"
    - echo "Trace context:\ $TRACEPARENT"
    - echo "Pipeline source:\ $CI_PIPELINE_SOURCE"
    - echo "Parent pipeline ID:\ $CI_PARENT_PIPELINE_ID"

# Production deployment
deploy-prod:
  stage: deploy-prod
  script:
    - echo "Deploying to production..."
    - echo "This deployment is traced back to parent pipeline"
    - sleep 5

# Export correlated traces
otel-export:
  stage: .post
  image:
    name: gitlab-otel-exporter:0.0.1
    entrypoint: [""]
  script:
    - export GITLAB_TOKEN=${CI_JOB_TOKEN}
    - echo "Exporting child pipeline traces..."
    - /cnb/process/cmd
  when: always
  allow_failure: true
